module Rails

  # CacheCache allow you to manage dynamically multiple groups of HTML5 manifests.
  # CacheCache use rails cache to store generated manifests.
  #
  class CacheCache

    # Constructor
    #
    def initialize(options = {}, &block)
      @memory_store = options.fetch(:memory_store, (ActiveSupport::Cache::MemoryStore.new rescue nil))
      @group = options.fetch(:group, :default)

      @cache = { }
      @network = { }
      @fallback = { }

      self.configure(&block) if block_given? and not self.cached
    end

    # Configure
    #
    def configure(&block)
      instance_eval(&block)
    end

    # Get / Set an entry into the cache section of the manifest
    #
    def cache(entry = nil)
      unless entry.nil?
        @cache[@group] ||= []
        @cache[@group] << entry
      end

      @cache[@group].flatten
    end

    # Get / Set an entry into the network section of the manifest
    #
    def network(entry = nil)
      unless entry.nil?
        @network[@group] ||= []
        @network[@group] << entry
      end

      @network[@group].flatten
    end

    # Get / Set an entry into the fallback section of the manifest
    #
    def fallback(entry = nil)
      unless entry.nil?
        @fallback[@group] ||= []
        @fallback[@group] << entry
      end

      @fallback[@group].flatten
    end

    # Save the current manifest
    #
    def save
      @memory_store.write(self.label, self.manifest) rescue nil
    end

    # Get the manifest
    #
    def manifest
      return (self.cached or self.generate)
    end

    # Get the manifest from cache ifp
    #
    def cached
       @memory_store.read(self.label) rescue nil
    end

    # Generate the manifest
    #
    def generate
      [
        'CACHE MANIFEST'  ,
        self.spoor        ,
        'CACHE:'          ,
        self.cache        ,
        'NETWORK:'        ,
        self.network      ,
        'FALLBACK:'       ,
        self.fallback     ,
      ].join("\n")
    end

    # Get / Set the current group
    #
    def group(group_name = nil)
      @group = group_name unless group_name.nil?
      @group
    end

    # Get the spoor of the manifest
    #
    def spoor
      "# generated by cache_cache"
    end

    # Get label
    #
    def label
      "cache_cache_#{@group}"
    end

    # Get the manifest
    #
    def to_s
      self.manifest
    end
  end
end